[auth]
secret_credentials_path = "" # Si usas archivo JSON de credenciales, pon la ruta; si usas client_id/secret directo, déjalo vacío o elimínalo según tu versión de la librería.
redirect_uri = "https://bioexplora-chile.onrender.com/oauth2callback"
cookie_key = "bioexplora_clave_super_secreta_987654321_clave"
cookie_name = "bioexplora_cookie"
client_id = "93862363283-jjbskrb1vmddccdvv4jg1750t2631eq0.apps.googleusercontent.com"
client_secret = "GOCSPX-Jwpj2NRWL8j1FeiUrQRksx-cy4"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
