[auth]
redirect_uri = "https://bioexplora-chile.onrender.com/~/+oauth2callback"
cookie_secret = "bioexplora_clave_super_secreta_987654321_clave"

[auth.google]
client_id = "938623263283-jjbskrb1vmddccdvv4jg1750t2631eq0.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
