[auth]
redirect_uri = "https://bioexplora-chile.onrender.com/oauth2callback"
cookie_secret = "bioexplora-clave_super_secreta_987654321_clave"

[auth.google]
client_id = "93862363283-jjbskrb1vmddccdvv4jg1750t2631eq0.apps.googleusercontent.com"
client_secret = "GOCSPX-Jwpj2NRWL8j1FeiUrQRksx-cy4"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
